version: 0.2

# Environment Variables:
# $S3_BUCKET:        The S3 Bucket that the static website will be deployed to.
# $LAMBDA_S3_BUCKET: The S3 Bucket that the lambda function code will be deployed to.
# $STACK_NAME:       The CloudFormation stack name that should be updated.
# $MAGIC_SECRET_KEY: The Magic SDK Secret key should be used by the backend.
# $REDIS_PORT:       The port number that Redis should be accessed over.
# $REDIS_HOST:       The hostname that Redis is available at.
# $REDIS_USE_TLS:    Whether to use TLS for the Redis connection.
# $REDIS_RECORDS_NAMESPACE: The namespace that records stored in redis should use.
# $REDIS_PASSWORD:   The password that should be used to access Redis.
# $FILES_STORAGE_CLASS: The S3 Storage class that file records should be stored in. See x-amz-storage-class in https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutObject.html
# $CLOUDFRONT_DISTRIBUTION: The ID of the CloudFront Distributation that should be invalidated once the build completes.

# Description:
# This buildspec is able to build and deploy the aux-auth package to AWS.
# It will build and deploy the static website to the S3_BUCKET environment variable,
# deploy the serverless lambda functions to LAMBDA_S3_BUCKET and update a CloudFormation
# stack called STACK_NAME with the MAGIC_SECRET_KEY, REDIS_PORT, REDIS_HOST, REDIS_USE_TLS, REDIS_RECORDS_NAMESPACE, REDIS_PASSWORD,
# and FILES_STORAGE_CLASS environment variables as parameters.
# Once the build is completed, you will need to go to CloudFormation and execute the new changeset in order for the Lambda functions to be deployed.

env:
    secrets-manager:
        MAGIC_SECRET_KEY: $SECRET_NAME:MAGIC_SECRET_KEY

phases:
    install:
        runtime-versions:
            nodejs: 14
        commands:
            - echo Executing Install Phase
        finally:
            - echo Executing Install Finally
    pre_build:
        commands:
            - echo Executing Pre Build Phase
            - npm ci
            - npm run bootstrap
        finally:
            - echo Executing Pre Build Finally
    build:
        commands:
            - echo Executing Build Phase

            - echo Building packages...
            - npm run build:libs
            - npm run build:auth
        finally:
            - echo Executing Build Finally
    post_build:
        commands:
            - echo Executing Post Build Phase
            - echo Copying Site to S3...
            - aws s3 sync src/aux-auth/web/dist $S3_BUCKET --delete

            - echo Deploying Lambda...
            - cd src/aux-auth/serverless/aws

            # Remove tests and original source
            - rm -rf ./__tests__
            - rm -rf ./src
            - rm -rf ./events
            - sam package --template-file template.yml --s3-bucket $LAMBDA_S3_BUCKET --output-template-file template-out.yaml
            - |
                sam deploy --template-file template-out.yaml --stack-name $STACK_NAME \
                  --capabilities CAPABILITY_IAM --no-fail-on-empty-changeset \
                  --no-execute-changeset \
                  --parameter-overrides MagicSecretKeyParameter=$MAGIC_SECRET_KEY RedisPortParameter=$REDIS_PORT RedisHostParameter="$REDIS_HOST" RedisUseTLSParameter=$REDIS_USE_TLS RedisRecordsNamespaceParameter=$REDIS_RECORDS_NAMESPACE RedisPasswordParameter="$REDIS_PASSWORD" FileRecordsS3StorageClassParameter="$FILES_STORAGE_CLASS" \
                  --tags Customer=casualos

            # - aws cloudformation deploy --template-file template.yml --stack-name $STACK_NAME --s3-bucket $LAMBDA_S3_BUCKET --no-execute-changeset --parameter-overrides MagicSecretKeyParameter=$MAGIC_SECRET_KEY

            - echo Invalidating CloudFront...
            - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION --paths "/*"
            - echo Done!
        finally:
            - echo Executing Post Build Finally
