name: Continuous Integration

on: [push, pull_request]

jobs:
    test:
        name: Test
        strategy:
            matrix:
                os: [ubuntu-latest, macOS-latest, windows-latest]
                node-version: [14.x]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: npm install and test
              run: |
                  npm ci
                  npm run bootstrap
                  npx jest --detectOpenHandles --forceExit --no-cache
              env:
                  CI: true
    build:
        name: Build AUX
        strategy:
            matrix:
                os: [ubuntu-latest, macOS-latest, windows-latest]
                node-version: [14.x]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: npm install and build
              run: |
                  npm ci
                  npm run bootstrap
                  npm run build
              env:
                  CI: true
    docs:
        name: Build Docs
        strategy:
            matrix:
                os: [ubuntu-latest, macOS-latest, windows-latest]
                node-version: [14.x]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: yarn install and build docs
              run: |
                  cd docs
                  yarn
                  yarn build
              env:
                  CI: true
